#!/usr/bin/env bash
# Script that Install Nginx
sudo apt update
sudo apt install nginx -y
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sed -i '/server_name _;/a\\terror_page 404 \/custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t\t}' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
service nginx restart
