#!/usr/bin/env bash
# Script that Install Nginx and add a new header variable
# shellcheck disable=SC2086
apt update
apt install nginx -y
command=$(hostnamectl | cut -d " " -f 6 | head -n 1)
sed -i 's/as directory, then fall back to displaying a 404./\n\t\tadd_header X-Served-By '"$command"';/' /etc/nginx/sites-available/default
service nginx restart 
