#!/usr/bin/env bash
# Start, stop, restart process

if [[ $1 == 'start' ]]
then
   ./manage_my_process &
   echo $$ > /var/run/my_process.pid
   echo "manage_my_process started"
elif [[ $1 == 'stop' ]]
then
    kill "$( pgrep "manage_my_process" -f )"
    rm -rf /var/run/my_process
    echo "manage_my_process stopped"
elif [[ $1 == 'restart' ]]
then
    kill "$( pgrep "manage_my_process" -f )"
    rm -rf /var/run/my_process
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
    


