#!/usr/bin/env bash
#

while IFS=":" read -r user pass userid grupId group homeDir shell  
do
        echo "The user $user is part of the $grupId gang, lives in $homeDir and rides $shell. $userid's place is protected by the passcode $pass, more info about the user here: $group"
done < /etc/passwd
