#!/usr/bin/env bash
# Learn to use Loops and coditionals

i=1
while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ $i == 8 ]
    then
        echo "good luck"
    else
        echo "Holberton school"
    fi
    
    ((i++))
done
