#!/usr/bin/env bash
# Change your home ip to resolve to 127.0.0.2
# Change facebook to resolve to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '/127.0.0.2/a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
