#!/usr/bin/env bash
# Fix nginx running at port 8080 and running as root
sed -i 's/80/8080' /etc/nginx/sites-enabled/default
chmod +rw /etc/nginx/nginx.conf
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
sudo -u nginx /etc/init.d/nginx start
